[package]
name = "meshroute"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
getopts = "0.2.23"
bson = { version = "3.1.0", features = ["serde", "serde_with-3"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
rsa = "0.9.10"
libc = "0.2.183"
chrono = "0.4.42"
sha2 = "0.10.9"
rand = "0.8.3"
chacha20poly1305 = "0.10.1"
num-traits = "0.2.19"
flate2 = "1.0.35"
